Repository neu25/hoosky-bot, pull requests merged in 2021-07, with the labels that each got.

#22 Implement course sections
  COMMANDS.md
  src/commands/course/_common.ts
  src/commands/course/subcommands/bulkCreate.ts
  src/commands/course/subcommands/classmates.ts
  src/commands/course/subcommands/create.ts
  src/commands/course/subcommands/index.ts
  src/commands/course/subcommands/join.ts
  src/commands/course/subcommands/leave.ts
  src/commands/course/subcommands/listJoined.ts
  src/commands/course/subcommands/roster.ts
  src/commands/pfp.ts
  src/format.ts
  src/repository/CourseRepo.ts
  src/repository/index.ts
  src/triggers/GUILD_CREATE/index.ts
  src/triggers/GUILD_CREATE/normalizeDatabase.ts
  src/triggers/GUILD_CREATE/syncCommands.ts
  src/triggers/GUILD_MEMBER_UPDATE/courseRole.ts
  src/utils.ts
Labels: enhancement

#41 Add guidelines for good commits and commit messages
  CONTRIBUTING.md
Labels: documentation

#49 Allow status messages
  src/commands/bot/subcommands/setStatus.ts
Labels: enhancement

#51 Add support for attachments in the say command
  package-lock.json
  package.json
  src/Api.ts
  src/Client.ts
  src/Discord/message.ts
  src/ExecutionContext.ts
  src/FollowUpManager.ts
  src/commands/course/subcommands/bulkCreate.ts
  src/commands/say.ts
  src/interactions/mail/reply.ts
Labels: bug

#17 Implement birthday commands
  COMMANDS.md
  package-lock.json
  package.json
  src/BaseContext.ts
  src/Discord/message.ts
  src/commands/birthday/_common.ts
  src/commands/birthday/index.ts
  src/commands/birthday/messageScheduler.ts
  src/commands/birthday/roleScheduler.ts
  src/commands/birthday/subcommands/index.ts
  src/commands/birthday/subcommands/list.ts
  src/commands/birthday/subcommands/messageAdd.ts
  src/commands/birthday/subcommands/messageDelete.ts
  src/commands/birthday/subcommands/messageList.ts
  src/commands/birthday/subcommands/set.ts
  src/commands/birthday/subcommands/setChannel.ts
  src/commands/birthday/subcommands/setRole.ts
  src/commands/birthday/subcommands/setSchedule.ts
  src/commands/birthday/subcommands/show.ts
  src/commands/birthday/subcommands/showSchedule.ts
  src/commands/birthday/subcommands/unset.ts
  src/commands/commands.ts
  src/commands/mute/subcommands/setup.ts
  src/database/constants.ts
  src/repository/BirthdayRepo.ts
  src/repository/ConfigRepo.ts
  src/repository/index.ts
  src/triggers/GUILD_CREATE/birthdayMessageScheduler.ts
  src/triggers/GUILD_CREATE/birthdayRoleScheduler.ts
  src/triggers/GUILD_CREATE/index.ts
  src/triggers/GUILD_CREATE/normalizeDatabase.ts
  src/utils.ts
Labels: enhancement
