Repository neu25/hoosky-bot, pull requests merged in 2021-06, with the labels that each got.

#12 Document Commands + Update README
  COMMANDS.md
  README.md
Labels: documentation

#20 Add mute setup command and refactor subcommands
  src/Api.ts
  src/Client.ts
  src/Discord/guild.ts
  src/Discord/index.ts
  src/Discord/permission.ts
  src/Permissions.ts
  src/SubCommand.ts
  src/commands/index.ts
  src/commands/mute/_common.ts
  src/commands/mute/index.ts
  src/commands/mute/mute.ts
  src/commands/mute/subcommands/add.ts
  src/commands/mute/subcommands/index.ts
  src/commands/mute/subcommands/remove.ts
  src/commands/mute/subcommands/setup.ts
  src/commands/mute/unmute.ts
  src/database/Database.ts
  src/database/constants.ts
  src/permissions.ts
  src/triggers/CHANNEL_UPDATE/mutedRole.ts
  src/triggers/GUILD_CREATE/index.ts
  src/triggers/GUILD_CREATE/mutedRole.ts
Labels: enhancement

#30 Caching and optimization
  .eslintrc.json
  src/Api.ts
  src/Cache.ts
  src/Client.ts
  src/CommandOption.ts
  src/Discord/guild.ts
  src/Discord/index.ts
  src/ExecutionContext.ts
  src/SubCommand.ts
  src/SubCommandGroup.ts
  src/Trigger.ts
  src/TriggerContext.ts
  src/commands/index.ts
  src/index.ts
  src/triggers/CHANNEL_UPDATE/mutedRole.ts
  src/triggers/GUILD_CREATE/syncCommands.ts
  src/triggers/GUILD_MEMBER_UPDATE/courseRole.ts
  src/triggers/GUILD_ROLE_DELETE/courseRole.ts
  src/triggers/index.ts
Labels: enhancement

#35 Implement course bulk creation and follow-up messages
  package-lock.json
  package.json
  src/Api.ts
  src/Client.ts
  src/Command.ts
  src/Discord/index.ts
  src/Discord/message.ts
  src/ExecutionContext.ts
  src/FollowUpManager.ts
  src/SubCommand.ts
  src/SubCommandGroup.ts
  src/Trigger.ts
  src/commands/course/_common.ts
  src/commands/course/subcommands/bulkCreate.ts
  src/commands/course/subcommands/create.ts
  src/commands/course/subcommands/index.ts
  src/commands/course/subcommands/join.ts
  src/commands/course/subcommands/leave.ts
  src/commands/course/subcommands/listJoined.ts
  src/index.ts
  src/repository/CourseRepo.ts
Labels: enhancement

#29 Add help command
  src/commands/_utils.ts
  src/commands/commands.ts
  src/commands/help.ts
  src/commands/index.ts
  src/format.ts
Labels: enhancement, wip
